### PR TITLE
Image uploader/fix file detection

### PR DESCRIPTION
**Pull request by ugogo**
Fix a couple of issues leading to weird states and visual glitches

### CODE REVIEW

**Comment by keanan** [comment]
Hey @ugo I tested story book and it seems the previous bug is back - if you select the same image twice it no longer shows in the preview.

**Comment by ugogo** [comment]
Hey @keanan, this bug has never been fixed 🤷‍♂ 
But... I just did 🙂

**Comment by keanan** [comment]
It was definitely fixed 🙂 I just double checked again in production

**Comment by ugogo** [comment]
My bad then 🙈

**Pull request merged**
