### PR TITLE
v2/move-components

### PR DESCRIPTION
**Pull request by ugogo**
Move actual components into a components-deprecated folder

### CODE REVIEW

**Comment by ugogo** [comment]
https://github.com/heetch/flamingo/pull/110

**Comment by obedparla** [comment]
You should also move a copy of `css` into the folder. That would help when migrating since we need to check the stylings etc

**Comment by ugogo** [comment]
@obedparla 

> You should also move a copy of css into the folder. That would help when migrating since we need to check the stylings etc

But we deleted those files 😅

**Comment by ugogo** [comment]
@obedparla Files are still accessible here https://github.com/heetch/flamingo/pull/116/files

**Comment by obedparla** [comment]
🤦‍♂ that's why I deprecated them the way I did. Without being able to access those files I think it's complicated to code. I had the `css` files open on one window and the new SC component on another. 

I wouldn't worry too much about PRs being dirty for now, we're making a lot of changes. WDYT if we add them back? (Sorry I should've mentioned this in the CSS removal PR instead 🤦‍♂ )

**Pull request closed without merging**
