### PR TITLE
In Figma the designers have a "concrete" flamingo color.

### PR DESCRIPTION
**Pull request by obedparla**
Not sure if the name makes sense but we use it quite a lot in the admin and would be nice to have it as a var.

### CODE REVIEW

**Comment by obedparla** [comment]
> What is its intent? Is it the default color? In which context is it used?

Elodie uses it mostly for borders, separators, that sort of thing.

**Comment by ugogo** [comment]
So should it be the default color?

**Comment by obedparla** [comment]
Sorry, I don't follow, the default color of what? 😅

**Comment by ugogo** [comment]
Of an icon 😄

**Pull request merged**
