### PR TITLE
Support isLoading on IconButton

### PR DESCRIPTION
**Pull request by Tahul**
I have been using Flamingo lately and encountered a problem using IconButton.

I wanted to implement a "Trash button", that displays the trashcan icon and the spinner while the DELETE call is made.

Using the "isLoading" attribute on a IconButton actually results in showing the spinner but not hiding the actual icon from the `icon` props passed to IconButton.

As it felt like a bug, I am submitting this pull request that fixes the problem.

I did not added the support for custom states in Storybook, even though they seem to work that was not needed on my side.

### CODE REVIEW

**Comment by tamarasaurus** [comment]
Hey @Tahul :wave: thanks for your contribution :slightly_smiling_face: We'll pass it on to the designers first and keep you updated

**Review by tamarasaurus — APPROVED** [review]

**Comment by tamarasaurus** [comment]
Hey @Tahul Sorry for the delay, it looks good from our side. Could you rebase your branch with master before I merge it? Thanks :slightly_smiling_face:

**Comment by Tahul** [comment]
Hey @tamarasaurus ; no worries.

I will be doing that soon, thanks again for the review.

**Comment by Tahul** [comment]
It's done @tamarasaurus :)

If anything else is needed, don't hesitate to ping me.

See ya 👋

**Pull request merged**
